[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bla = "J5qyvFxq8JprXYyo4n5qGZ8cYuCZUKi6wEzuSmDTPEgB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ohaddahan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
