/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link MerkleAirDropperSource}
 * @category Accounts
 * @category generated
 */
export type MerkleAirDropperSourceArgs = {
  bump: number
  seed: beet.bignum
  signer: web3.PublicKey
  merkleRoot: number[] /* size: 32 */
  mint: web3.PublicKey
  tokenAccount: web3.PublicKey
  maxTotalClaim: beet.bignum
  maxNumNodes: beet.bignum
  totalAmountClaimed: beet.bignum
  numNodesClaimed: beet.bignum
  leavesLen: beet.bignum
}

export const merkleAirDropperSourceDiscriminator = [
  157, 253, 195, 245, 131, 174, 254, 54,
]
/**
 * Holds the data for the {@link MerkleAirDropperSource} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class MerkleAirDropperSource implements MerkleAirDropperSourceArgs {
  private constructor(
    readonly bump: number,
    readonly seed: beet.bignum,
    readonly signer: web3.PublicKey,
    readonly merkleRoot: number[] /* size: 32 */,
    readonly mint: web3.PublicKey,
    readonly tokenAccount: web3.PublicKey,
    readonly maxTotalClaim: beet.bignum,
    readonly maxNumNodes: beet.bignum,
    readonly totalAmountClaimed: beet.bignum,
    readonly numNodesClaimed: beet.bignum,
    readonly leavesLen: beet.bignum
  ) {}

  /**
   * Creates a {@link MerkleAirDropperSource} instance from the provided args.
   */
  static fromArgs(args: MerkleAirDropperSourceArgs) {
    return new MerkleAirDropperSource(
      args.bump,
      args.seed,
      args.signer,
      args.merkleRoot,
      args.mint,
      args.tokenAccount,
      args.maxTotalClaim,
      args.maxNumNodes,
      args.totalAmountClaimed,
      args.numNodesClaimed,
      args.leavesLen
    )
  }

  /**
   * Deserializes the {@link MerkleAirDropperSource} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [MerkleAirDropperSource, number] {
    return MerkleAirDropperSource.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link MerkleAirDropperSource} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<MerkleAirDropperSource> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(
        `Unable to find MerkleAirDropperSource account at ${address}`
      )
    }
    return MerkleAirDropperSource.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '6yGnfw6ahHDQXequrUaQNv6UxbdmceQYGvZUtFDFrHqR'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(
      programId,
      merkleAirDropperSourceBeet
    )
  }

  /**
   * Deserializes the {@link MerkleAirDropperSource} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(
    buf: Buffer,
    offset = 0
  ): [MerkleAirDropperSource, number] {
    return merkleAirDropperSourceBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link MerkleAirDropperSource} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return merkleAirDropperSourceBeet.serialize({
      accountDiscriminator: merkleAirDropperSourceDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link MerkleAirDropperSource}
   */
  static get byteSize() {
    return merkleAirDropperSourceBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link MerkleAirDropperSource} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      MerkleAirDropperSource.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link MerkleAirDropperSource} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === MerkleAirDropperSource.byteSize
  }

  /**
   * Returns a readable version of {@link MerkleAirDropperSource} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      seed: (() => {
        const x = <{ toNumber: () => number }>this.seed
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      signer: this.signer.toBase58(),
      merkleRoot: this.merkleRoot,
      mint: this.mint.toBase58(),
      tokenAccount: this.tokenAccount.toBase58(),
      maxTotalClaim: (() => {
        const x = <{ toNumber: () => number }>this.maxTotalClaim
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      maxNumNodes: (() => {
        const x = <{ toNumber: () => number }>this.maxNumNodes
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      totalAmountClaimed: (() => {
        const x = <{ toNumber: () => number }>this.totalAmountClaimed
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      numNodesClaimed: (() => {
        const x = <{ toNumber: () => number }>this.numNodesClaimed
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      leavesLen: (() => {
        const x = <{ toNumber: () => number }>this.leavesLen
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const merkleAirDropperSourceBeet = new beet.BeetStruct<
  MerkleAirDropperSource,
  MerkleAirDropperSourceArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['seed', beet.u64],
    ['signer', beetSolana.publicKey],
    ['merkleRoot', beet.uniformFixedSizeArray(beet.u8, 32)],
    ['mint', beetSolana.publicKey],
    ['tokenAccount', beetSolana.publicKey],
    ['maxTotalClaim', beet.u64],
    ['maxNumNodes', beet.u64],
    ['totalAmountClaimed', beet.u64],
    ['numNodesClaimed', beet.u64],
    ['leavesLen', beet.u64],
  ],
  MerkleAirDropperSource.fromArgs,
  'MerkleAirDropperSource'
)
