/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  CreateMerkleAirDropperArgs,
  createMerkleAirDropperArgsBeet,
} from '../types/CreateMerkleAirDropperArgs'

/**
 * @category Instructions
 * @category CreateMerkleAirDropper
 * @category generated
 */
export type CreateMerkleAirDropperInstructionArgs = {
  args: CreateMerkleAirDropperArgs
}
/**
 * @category Instructions
 * @category CreateMerkleAirDropper
 * @category generated
 */
export const createMerkleAirDropperStruct = new beet.BeetArgsStruct<
  CreateMerkleAirDropperInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['args', createMerkleAirDropperArgsBeet],
  ],
  'CreateMerkleAirDropperInstructionArgs'
)
/**
 * Accounts required by the _createMerkleAirDropper_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] signerTokenAccount
 * @property [_writable_] merkleAirDropper
 * @property [_writable_] merkleAirDropperTokenAccount
 * @property [] mint
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category CreateMerkleAirDropper
 * @category generated
 */
export type CreateMerkleAirDropperInstructionAccounts = {
  signer: web3.PublicKey
  signerTokenAccount: web3.PublicKey
  merkleAirDropper: web3.PublicKey
  merkleAirDropperTokenAccount: web3.PublicKey
  mint: web3.PublicKey
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createMerkleAirDropperInstructionDiscriminator = [
  22, 212, 196, 45, 199, 36, 156, 100,
]

/**
 * Creates a _CreateMerkleAirDropper_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateMerkleAirDropper
 * @category generated
 */
export function createCreateMerkleAirDropperInstruction(
  accounts: CreateMerkleAirDropperInstructionAccounts,
  args: CreateMerkleAirDropperInstructionArgs,
  programId = new web3.PublicKey('J5qyvFxq8JprXYyo4n5qGZ8cYuCZUKi6wEzuSmDTPEgB')
) {
  const [data] = createMerkleAirDropperStruct.serialize({
    instructionDiscriminator: createMerkleAirDropperInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.signerTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.merkleAirDropper,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.merkleAirDropperTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
