/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type CreateMerkleAirDropperArgs = {
  merkleRoot: number[] /* size: 32 */
  seed: beet.bignum
  maxTotalClaim: beet.bignum
  maxNumNodes: beet.bignum
  leavesLen: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const createMerkleAirDropperArgsBeet =
  new beet.BeetArgsStruct<CreateMerkleAirDropperArgs>(
    [
      ['merkleRoot', beet.uniformFixedSizeArray(beet.u8, 32)],
      ['seed', beet.u64],
      ['maxTotalClaim', beet.u64],
      ['maxNumNodes', beet.u64],
      ['leavesLen', beet.u64],
    ],
    'CreateMerkleAirDropperArgs'
  )
