//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

      pub(crate) mod merkle_air_dropper;
  
      pub use self::merkle_air_dropper::MerkleAirDropperError;
  
