//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_program::pubkey::Pubkey;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;


#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct MerkleAirDropperSource {
pub discriminator: [u8; 8],
pub bump: u8,
pub seed: u64,
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub signer: Pubkey,
pub merkle_root: [u8; 32],
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub mint: Pubkey,
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub token_account: Pubkey,
pub max_total_claim: u64,
pub max_num_nodes: u64,
pub total_amount_claimed: u64,
pub num_nodes_claimed: u64,
pub leaves_len: u64,
}


impl MerkleAirDropperSource {
      pub const LEN: usize = 185;
  
  
  
  #[inline(always)]
  pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
    let mut data = data;
    Self::deserialize(&mut data)
  }
}

impl<'a> TryFrom<&solana_program::account_info::AccountInfo<'a>> for MerkleAirDropperSource {
  type Error = std::io::Error;

  fn try_from(account_info: &solana_program::account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
      let mut data: &[u8] = &(*account_info.data).borrow();
      Self::deserialize(&mut data)
  }
}

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountDeserialize for MerkleAirDropperSource {
      fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
      }
  }

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountSerialize for MerkleAirDropperSource {}

  #[cfg(feature = "anchor")]
  impl anchor_lang::Owner for MerkleAirDropperSource {
      fn owner() -> Pubkey {
        crate::MERKLE_AIR_DROPPER_ID
      }
  }

  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::IdlBuild for MerkleAirDropperSource {}

  
  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::Discriminator for MerkleAirDropperSource {
    const DISCRIMINATOR: [u8; 8] = [0; 8];
  }

