//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

/// Accounts.
pub struct CreateMerkleAirDropperSource {
      
              
          pub signer: solana_program::pubkey::Pubkey,
          
              
          pub signer_token_account: solana_program::pubkey::Pubkey,
          
              
          pub merkle_air_dropper_source: solana_program::pubkey::Pubkey,
          
              
          pub merkle_air_dropper_source_token_account: solana_program::pubkey::Pubkey,
          
              
          pub mint: solana_program::pubkey::Pubkey,
          
              
          pub system_program: solana_program::pubkey::Pubkey,
          
              
          pub token_program: solana_program::pubkey::Pubkey,
          
              
          pub associated_token_program: solana_program::pubkey::Pubkey,
          
              
          pub rent: solana_program::pubkey::Pubkey,
      }

impl CreateMerkleAirDropperSource {
  pub fn instruction(&self, args: CreateMerkleAirDropperSourceInstructionArgs) -> solana_program::instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: CreateMerkleAirDropperSourceInstructionArgs, remaining_accounts: &[solana_program::instruction::AccountMeta]) -> solana_program::instruction::Instruction {
    let mut accounts = Vec::with_capacity(9+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new(
            self.signer,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.signer_token_account,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.merkle_air_dropper_source,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.merkle_air_dropper_source_token_account,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.mint,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.token_program,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.associated_token_program,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.rent,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = CreateMerkleAirDropperSourceInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_program::instruction::Instruction {
      program_id: crate::MERKLE_AIR_DROPPER_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct CreateMerkleAirDropperSourceInstructionData {
            discriminator: [u8; 8],
                                    }

impl CreateMerkleAirDropperSourceInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [8, 61, 14, 197, 54, 52, 183, 61],
                                                                                        }
  }
}

impl Default for CreateMerkleAirDropperSourceInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct CreateMerkleAirDropperSourceInstructionArgs {
                  pub merkle_root: [u8; 32],
                pub seed: u64,
                pub max_total_claim: u64,
                pub max_num_nodes: u64,
                pub leaves_len: u64,
      }


/// Instruction builder for `CreateMerkleAirDropperSource`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` signer
                ///   1. `[writable]` signer_token_account
                ///   2. `[writable]` merkle_air_dropper_source
                ///   3. `[writable]` merkle_air_dropper_source_token_account
          ///   4. `[]` mint
                ///   5. `[optional]` system_program (default to `11111111111111111111111111111111`)
                ///   6. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
          ///   7. `[]` associated_token_program
                ///   8. `[optional]` rent (default to `SysvarRent111111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct CreateMerkleAirDropperSourceBuilder {
            signer: Option<solana_program::pubkey::Pubkey>,
                signer_token_account: Option<solana_program::pubkey::Pubkey>,
                merkle_air_dropper_source: Option<solana_program::pubkey::Pubkey>,
                merkle_air_dropper_source_token_account: Option<solana_program::pubkey::Pubkey>,
                mint: Option<solana_program::pubkey::Pubkey>,
                system_program: Option<solana_program::pubkey::Pubkey>,
                token_program: Option<solana_program::pubkey::Pubkey>,
                associated_token_program: Option<solana_program::pubkey::Pubkey>,
                rent: Option<solana_program::pubkey::Pubkey>,
                        merkle_root: Option<[u8; 32]>,
                seed: Option<u64>,
                max_total_claim: Option<u64>,
                max_num_nodes: Option<u64>,
                leaves_len: Option<u64>,
        __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl CreateMerkleAirDropperSourceBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn signer(&mut self, signer: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.signer = Some(signer);
                    self
    }
            #[inline(always)]
    pub fn signer_token_account(&mut self, signer_token_account: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.signer_token_account = Some(signer_token_account);
                    self
    }
            #[inline(always)]
    pub fn merkle_air_dropper_source(&mut self, merkle_air_dropper_source: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.merkle_air_dropper_source = Some(merkle_air_dropper_source);
                    self
    }
            #[inline(always)]
    pub fn merkle_air_dropper_source_token_account(&mut self, merkle_air_dropper_source_token_account: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.merkle_air_dropper_source_token_account = Some(merkle_air_dropper_source_token_account);
                    self
    }
            #[inline(always)]
    pub fn mint(&mut self, mint: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.mint = Some(mint);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
            /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
#[inline(always)]
    pub fn token_program(&mut self, token_program: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.token_program = Some(token_program);
                    self
    }
            #[inline(always)]
    pub fn associated_token_program(&mut self, associated_token_program: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.associated_token_program = Some(associated_token_program);
                    self
    }
            /// `[optional account, default to 'SysvarRent111111111111111111111111111111111']`
#[inline(always)]
    pub fn rent(&mut self, rent: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.rent = Some(rent);
                    self
    }
                    #[inline(always)]
      pub fn merkle_root(&mut self, merkle_root: [u8; 32]) -> &mut Self {
        self.merkle_root = Some(merkle_root);
        self
      }
                #[inline(always)]
      pub fn seed(&mut self, seed: u64) -> &mut Self {
        self.seed = Some(seed);
        self
      }
                #[inline(always)]
      pub fn max_total_claim(&mut self, max_total_claim: u64) -> &mut Self {
        self.max_total_claim = Some(max_total_claim);
        self
      }
                #[inline(always)]
      pub fn max_num_nodes(&mut self, max_num_nodes: u64) -> &mut Self {
        self.max_num_nodes = Some(max_num_nodes);
        self
      }
                #[inline(always)]
      pub fn leaves_len(&mut self, leaves_len: u64) -> &mut Self {
        self.leaves_len = Some(leaves_len);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_program::instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_program::instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_program::instruction::Instruction {
    let accounts = CreateMerkleAirDropperSource {
                              signer: self.signer.expect("signer is not set"),
                                        signer_token_account: self.signer_token_account.expect("signer_token_account is not set"),
                                        merkle_air_dropper_source: self.merkle_air_dropper_source.expect("merkle_air_dropper_source is not set"),
                                        merkle_air_dropper_source_token_account: self.merkle_air_dropper_source_token_account.expect("merkle_air_dropper_source_token_account is not set"),
                                        mint: self.mint.expect("mint is not set"),
                                        system_program: self.system_program.unwrap_or(solana_program::pubkey!("11111111111111111111111111111111")),
                                        token_program: self.token_program.unwrap_or(solana_program::pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")),
                                        associated_token_program: self.associated_token_program.expect("associated_token_program is not set"),
                                        rent: self.rent.unwrap_or(solana_program::pubkey!("SysvarRent111111111111111111111111111111111")),
                      };
          let args = CreateMerkleAirDropperSourceInstructionArgs {
                                                              merkle_root: self.merkle_root.clone().expect("merkle_root is not set"),
                                                                  seed: self.seed.clone().expect("seed is not set"),
                                                                  max_total_claim: self.max_total_claim.clone().expect("max_total_claim is not set"),
                                                                  max_num_nodes: self.max_num_nodes.clone().expect("max_num_nodes is not set"),
                                                                  leaves_len: self.leaves_len.clone().expect("leaves_len is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `create_merkle_air_dropper_source` CPI accounts.
  pub struct CreateMerkleAirDropperSourceCpiAccounts<'a, 'b> {
          
                    
              pub signer: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub signer_token_account: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub merkle_air_dropper_source: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub merkle_air_dropper_source_token_account: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub mint: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub token_program: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub associated_token_program: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub rent: &'b solana_program::account_info::AccountInfo<'a>,
            }

/// `create_merkle_air_dropper_source` CPI instruction.
pub struct CreateMerkleAirDropperSourceCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_program::account_info::AccountInfo<'a>,
      
              
          pub signer: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub signer_token_account: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub merkle_air_dropper_source: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub merkle_air_dropper_source_token_account: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub mint: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub token_program: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub associated_token_program: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub rent: &'b solana_program::account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: CreateMerkleAirDropperSourceInstructionArgs,
  }

impl<'a, 'b> CreateMerkleAirDropperSourceCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_program::account_info::AccountInfo<'a>,
          accounts: CreateMerkleAirDropperSourceCpiAccounts<'a, 'b>,
              args: CreateMerkleAirDropperSourceInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              signer: accounts.signer,
              signer_token_account: accounts.signer_token_account,
              merkle_air_dropper_source: accounts.merkle_air_dropper_source,
              merkle_air_dropper_source_token_account: accounts.merkle_air_dropper_source_token_account,
              mint: accounts.mint,
              system_program: accounts.system_program,
              token_program: accounts.token_program,
              associated_token_program: accounts.associated_token_program,
              rent: accounts.rent,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program::entrypoint::ProgramResult {
    let mut accounts = Vec::with_capacity(9+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new(
            *self.signer.key,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.signer_token_account.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.merkle_air_dropper_source.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.merkle_air_dropper_source_token_account.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.mint.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.associated_token_program.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.rent.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_program::instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = CreateMerkleAirDropperSourceInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_program::instruction::Instruction {
      program_id: crate::MERKLE_AIR_DROPPER_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(10 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.signer.clone());
                        account_infos.push(self.signer_token_account.clone());
                        account_infos.push(self.merkle_air_dropper_source.clone());
                        account_infos.push(self.merkle_air_dropper_source_token_account.clone());
                        account_infos.push(self.mint.clone());
                        account_infos.push(self.system_program.clone());
                        account_infos.push(self.token_program.clone());
                        account_infos.push(self.associated_token_program.clone());
                        account_infos.push(self.rent.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_program::program::invoke(&instruction, &account_infos)
    } else {
      solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `CreateMerkleAirDropperSource` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` signer
                ///   1. `[writable]` signer_token_account
                ///   2. `[writable]` merkle_air_dropper_source
                ///   3. `[writable]` merkle_air_dropper_source_token_account
          ///   4. `[]` mint
          ///   5. `[]` system_program
          ///   6. `[]` token_program
          ///   7. `[]` associated_token_program
          ///   8. `[]` rent
#[derive(Clone, Debug)]
pub struct CreateMerkleAirDropperSourceCpiBuilder<'a, 'b> {
  instruction: Box<CreateMerkleAirDropperSourceCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CreateMerkleAirDropperSourceCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(CreateMerkleAirDropperSourceCpiBuilderInstruction {
      __program: program,
              signer: None,
              signer_token_account: None,
              merkle_air_dropper_source: None,
              merkle_air_dropper_source_token_account: None,
              mint: None,
              system_program: None,
              token_program: None,
              associated_token_program: None,
              rent: None,
                                            merkle_root: None,
                                seed: None,
                                max_total_claim: None,
                                max_num_nodes: None,
                                leaves_len: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.signer = Some(signer);
                    self
    }
      #[inline(always)]
    pub fn signer_token_account(&mut self, signer_token_account: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.signer_token_account = Some(signer_token_account);
                    self
    }
      #[inline(always)]
    pub fn merkle_air_dropper_source(&mut self, merkle_air_dropper_source: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.merkle_air_dropper_source = Some(merkle_air_dropper_source);
                    self
    }
      #[inline(always)]
    pub fn merkle_air_dropper_source_token_account(&mut self, merkle_air_dropper_source_token_account: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.merkle_air_dropper_source_token_account = Some(merkle_air_dropper_source_token_account);
                    self
    }
      #[inline(always)]
    pub fn mint(&mut self, mint: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.mint = Some(mint);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
      #[inline(always)]
    pub fn token_program(&mut self, token_program: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.token_program = Some(token_program);
                    self
    }
      #[inline(always)]
    pub fn associated_token_program(&mut self, associated_token_program: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.associated_token_program = Some(associated_token_program);
                    self
    }
      #[inline(always)]
    pub fn rent(&mut self, rent: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.rent = Some(rent);
                    self
    }
                    #[inline(always)]
      pub fn merkle_root(&mut self, merkle_root: [u8; 32]) -> &mut Self {
        self.instruction.merkle_root = Some(merkle_root);
        self
      }
                #[inline(always)]
      pub fn seed(&mut self, seed: u64) -> &mut Self {
        self.instruction.seed = Some(seed);
        self
      }
                #[inline(always)]
      pub fn max_total_claim(&mut self, max_total_claim: u64) -> &mut Self {
        self.instruction.max_total_claim = Some(max_total_claim);
        self
      }
                #[inline(always)]
      pub fn max_num_nodes(&mut self, max_num_nodes: u64) -> &mut Self {
        self.instruction.max_num_nodes = Some(max_num_nodes);
        self
      }
                #[inline(always)]
      pub fn leaves_len(&mut self, leaves_len: u64) -> &mut Self {
        self.instruction.leaves_len = Some(leaves_len);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_program::account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
          let args = CreateMerkleAirDropperSourceInstructionArgs {
                                                              merkle_root: self.instruction.merkle_root.clone().expect("merkle_root is not set"),
                                                                  seed: self.instruction.seed.clone().expect("seed is not set"),
                                                                  max_total_claim: self.instruction.max_total_claim.clone().expect("max_total_claim is not set"),
                                                                  max_num_nodes: self.instruction.max_num_nodes.clone().expect("max_num_nodes is not set"),
                                                                  leaves_len: self.instruction.leaves_len.clone().expect("leaves_len is not set"),
                                    };
        let instruction = CreateMerkleAirDropperSourceCpi {
        __program: self.instruction.__program,
                  
          signer: self.instruction.signer.expect("signer is not set"),
                  
          signer_token_account: self.instruction.signer_token_account.expect("signer_token_account is not set"),
                  
          merkle_air_dropper_source: self.instruction.merkle_air_dropper_source.expect("merkle_air_dropper_source is not set"),
                  
          merkle_air_dropper_source_token_account: self.instruction.merkle_air_dropper_source_token_account.expect("merkle_air_dropper_source_token_account is not set"),
                  
          mint: self.instruction.mint.expect("mint is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                  
          token_program: self.instruction.token_program.expect("token_program is not set"),
                  
          associated_token_program: self.instruction.associated_token_program.expect("associated_token_program is not set"),
                  
          rent: self.instruction.rent.expect("rent is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct CreateMerkleAirDropperSourceCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_program::account_info::AccountInfo<'a>,
            signer: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                signer_token_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                merkle_air_dropper_source: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                merkle_air_dropper_source_token_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                mint: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                token_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                associated_token_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                rent: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                        merkle_root: Option<[u8; 32]>,
                seed: Option<u64>,
                max_total_claim: Option<u64>,
                max_num_nodes: Option<u64>,
                leaves_len: Option<u64>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)>,
}

