[package]
name = "merkle-air-dropper"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "merkle_air_dropper"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
common = { path = "../../libs/common" }
anchor-lang = { workspace = true, features = ["init-if-needed"] }
anchor-spl = { workspace = true, features = ["spl-associated-token-account", "spl-token", "metadata"] }
arrayref = { workspace = true }
anchor-lang-idl = { workspace = true, features = ["convert"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
rs_merkle = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
solana-sdk = { workspace = true }