//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_program::{pubkey, pubkey::Pubkey};


  /// `merkle_air_dropper` program ID.
  pub const MERKLE_AIR_DROPPER_ID: Pubkey = pubkey!("");

