/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link AirDropStatus}
 * @category Accounts
 * @category generated
 */
export type AirDropStatusArgs = {
  bump: number
  isClaimed: boolean
  claimant: web3.PublicKey
  mint: web3.PublicKey
  merkleAirDropper: web3.PublicKey
  claimedAt: beet.bignum
  amount: beet.bignum
}

export const airDropStatusDiscriminator = [207, 179, 91, 45, 210, 84, 85, 183]
/**
 * Holds the data for the {@link AirDropStatus} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class AirDropStatus implements AirDropStatusArgs {
  private constructor(
    readonly bump: number,
    readonly isClaimed: boolean,
    readonly claimant: web3.PublicKey,
    readonly mint: web3.PublicKey,
    readonly merkleAirDropper: web3.PublicKey,
    readonly claimedAt: beet.bignum,
    readonly amount: beet.bignum
  ) {}

  /**
   * Creates a {@link AirDropStatus} instance from the provided args.
   */
  static fromArgs(args: AirDropStatusArgs) {
    return new AirDropStatus(
      args.bump,
      args.isClaimed,
      args.claimant,
      args.mint,
      args.merkleAirDropper,
      args.claimedAt,
      args.amount
    )
  }

  /**
   * Deserializes the {@link AirDropStatus} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [AirDropStatus, number] {
    return AirDropStatus.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link AirDropStatus} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<AirDropStatus> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find AirDropStatus account at ${address}`)
    }
    return AirDropStatus.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '6yGnfw6ahHDQXequrUaQNv6UxbdmceQYGvZUtFDFrHqR'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, airDropStatusBeet)
  }

  /**
   * Deserializes the {@link AirDropStatus} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [AirDropStatus, number] {
    return airDropStatusBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link AirDropStatus} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return airDropStatusBeet.serialize({
      accountDiscriminator: airDropStatusDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link AirDropStatus}
   */
  static get byteSize() {
    return airDropStatusBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link AirDropStatus} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      AirDropStatus.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link AirDropStatus} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === AirDropStatus.byteSize
  }

  /**
   * Returns a readable version of {@link AirDropStatus} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      isClaimed: this.isClaimed,
      claimant: this.claimant.toBase58(),
      mint: this.mint.toBase58(),
      merkleAirDropper: this.merkleAirDropper.toBase58(),
      claimedAt: (() => {
        const x = <{ toNumber: () => number }>this.claimedAt
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      amount: (() => {
        const x = <{ toNumber: () => number }>this.amount
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const airDropStatusBeet = new beet.BeetStruct<
  AirDropStatus,
  AirDropStatusArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['isClaimed', beet.bool],
    ['claimant', beetSolana.publicKey],
    ['mint', beetSolana.publicKey],
    ['merkleAirDropper', beetSolana.publicKey],
    ['claimedAt', beet.i64],
    ['amount', beet.u64],
  ],
  AirDropStatus.fromArgs,
  'AirDropStatus'
)
