/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link ClaimAirDropStatus}
 * @category Accounts
 * @category generated
 */
export type ClaimAirDropStatusArgs = {
  bump: number
  isClaimed: boolean
  claimant: web3.PublicKey
  mint: web3.PublicKey
  merkleAirDropper: web3.PublicKey
  claimedAt: beet.bignum
  amount: beet.bignum
}

export const claimAirDropStatusDiscriminator = [
  110, 134, 151, 44, 209, 90, 249, 144,
]
/**
 * Holds the data for the {@link ClaimAirDropStatus} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class ClaimAirDropStatus implements ClaimAirDropStatusArgs {
  private constructor(
    readonly bump: number,
    readonly isClaimed: boolean,
    readonly claimant: web3.PublicKey,
    readonly mint: web3.PublicKey,
    readonly merkleAirDropper: web3.PublicKey,
    readonly claimedAt: beet.bignum,
    readonly amount: beet.bignum
  ) {}

  /**
   * Creates a {@link ClaimAirDropStatus} instance from the provided args.
   */
  static fromArgs(args: ClaimAirDropStatusArgs) {
    return new ClaimAirDropStatus(
      args.bump,
      args.isClaimed,
      args.claimant,
      args.mint,
      args.merkleAirDropper,
      args.claimedAt,
      args.amount
    )
  }

  /**
   * Deserializes the {@link ClaimAirDropStatus} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [ClaimAirDropStatus, number] {
    return ClaimAirDropStatus.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link ClaimAirDropStatus} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<ClaimAirDropStatus> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find ClaimAirDropStatus account at ${address}`)
    }
    return ClaimAirDropStatus.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'J5qyvFxq8JprXYyo4n5qGZ8cYuCZUKi6wEzuSmDTPEgB'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, claimAirDropStatusBeet)
  }

  /**
   * Deserializes the {@link ClaimAirDropStatus} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [ClaimAirDropStatus, number] {
    return claimAirDropStatusBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link ClaimAirDropStatus} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return claimAirDropStatusBeet.serialize({
      accountDiscriminator: claimAirDropStatusDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link ClaimAirDropStatus}
   */
  static get byteSize() {
    return claimAirDropStatusBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link ClaimAirDropStatus} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      ClaimAirDropStatus.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link ClaimAirDropStatus} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === ClaimAirDropStatus.byteSize
  }

  /**
   * Returns a readable version of {@link ClaimAirDropStatus} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      isClaimed: this.isClaimed,
      claimant: this.claimant.toBase58(),
      mint: this.mint.toBase58(),
      merkleAirDropper: this.merkleAirDropper.toBase58(),
      claimedAt: (() => {
        const x = <{ toNumber: () => number }>this.claimedAt
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      amount: (() => {
        const x = <{ toNumber: () => number }>this.amount
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const claimAirDropStatusBeet = new beet.BeetStruct<
  ClaimAirDropStatus,
  ClaimAirDropStatusArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['isClaimed', beet.bool],
    ['claimant', beetSolana.publicKey],
    ['mint', beetSolana.publicKey],
    ['merkleAirDropper', beetSolana.publicKey],
    ['claimedAt', beet.i64],
    ['amount', beet.u64],
  ],
  ClaimAirDropStatus.fromArgs,
  'ClaimAirDropStatus'
)
